#!/usr/bin/env php
<?php

// TODO: Console Repository
define('SUNA_START', microtime(true));

$filesValidators = [
    __DIR__.'/vendor/autoload.php',
    __DIR__.'/bootstrap/app.php'
];

foreach ($filesValidators as $fV) {
    if(!file_exists($fV)) {
        throw new Exception('Application not implemented', 501);
    }
}

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Suna\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Suna\Console\Input\ArgvInput,
    new Suna\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);